### PR TITLE
Create wordinfos in lesson update

### PR DESCRIPTION
**Pull request by mwitte98**
Related Issue #65 

Changes:
- Lesson update endpoint
  - Update lesson attributes
  - Create/edit/destroy wordinfos, roots, forms, synonyms, antonyms, and sentences
- Lesson wordinfo relationship changed to one-to-many

### CODE REVIEW

**Comment by djrenren** [comment]
I know we haven't been doing this for most of the project but could we get a test or two for this? It's complex enough behavior that lends itself well to testing.

**Comment by mwitte98** [comment]
Yeah I'll do some tests, but I'll have them in a separate PR

**Comment by mwitte98** [comment]
This is ready to be reviewed. Description of how creating, editing, and destroying works:

if a wordinfo, root, form, etc. has an id, it is updated
if it doesn't have an id, it is created
include `'_destroy': true` to destroy a wordinfo, root, form, etc.

**Review by 7imbrook — APPROVED** [review]
Defiantly wanna see tests for this, just to verify

**Pull request merged**
