### PR TITLE
Global Toast errors

### PR DESCRIPTION
**Pull request by 7imbrook**
Using 'error_push' action type, add to the global error queue to be displayed

### CODE REVIEW

**Review by mwitte98 — COMMENTED** [review]
@7imbrook why do you catch an error multiple times instead of catching it once higher up?

**Comment by 7imbrook** [comment]
@mwitte98 can you show me an example of what you mean

**Comment by mwitte98** [comment]
@7imbrook in [lesson.ts](https://github.com/teamdotjs/v2/blob/06e16e23284ca2d33cbdb8cddac808347c43a142/client/src/actions/lesson.ts#L44), the 4 functions all contain:
`.catch((err: Error) => {
            dispatch({
                type: 'error_push',
                error: err.message
            });
        })`

In react, is there somewhere higher up where this code can be used once? If for some reason we have to chance the code inside the catch, we'll have to change it everywhere.

In rails, all controllers inherit from ApplicationController so, for example, the not found error can be caught in ApplicationController instead of catching each one in the controller function where it originates. I would think something similar could be done in react as well, but not sure.

**Comment by 7imbrook** [comment]
@mwitte98 no there is no way to 'correctly' globally catch errors. The global toast errors should be explicitly sent by us because we may still want to try something else on the client after notifying. And we should be catching errors everywhere anyway, and not defer them to the some other global catcher.

**Review by mwitte98 — APPROVED** [review]

**Pull request merged**
