### PR TITLE
Rename lesson instructor to owner and lesson endpoints

### PR DESCRIPTION
**Pull request by mwitte98**
Related Issue #65 

Changes:
- Rename lesson instructor to owner
- Complete remaining lesson endpoints except removing a word

### CODE REVIEW

**Comment by djrenren** [comment]
It seems to me, word creation should be implicit in lesson creation. That is, there's no reason for the client to juggle creating words. It's useful on the backend for correlating word_infos and providing suggestions but I don't think we want to expose that.

**Comment by mwitte98** [comment]
@djrenren I thought that in lesson creation you wanted to create a lesson id without having to provide anything else? Or are you saying that lesson update should handle word creation?

**Review by 7imbrook — APPROVED** [review]

**Comment by djrenren** [comment]
@mwitte98 Sorry was saying that lesson update should handle word creation.

**Comment by mwitte98** [comment]
@djrenren I'm okay with this and will get it done tonight. I'm assuming wordinfo creation will only contain a word and any roots, synonyms, etc. can be added to that word through wordinfo update. Are you expecting this or something different on the front end?

**Pull request merged**
