### PR TITLE
Submit answer endpoint

### PR DESCRIPTION
**Pull request by mwitte98**
Related Issue #150 

Changes:
- `POST` `{ value: '' }` to `/api/question/:id/submit_answer`
- Returns `{ true }` or `{ false }`
- Tests

### CODE REVIEW

**Comment by 7imbrook** [comment]
@mwitte98 by returns `{ true }` and `{ false }` do you mean `{ "status": true }` etc...

**Comment by mwitte98** [comment]
@7imbrook no it's either `{ true }` or `{ false }`. It's the same as `/api/user/email_taken`. If we change it here, we should probably change it there as well.

**Comment by 7imbrook** [comment]
@mwitte98 you mean `true` or `false`?

**Comment by mwitte98** [comment]
@7imbrook yes, it only returns `true` or `false`. There's no keys in the hash

**Review by 7imbrook — APPROVED** [review]
I thought you we're returning a body `{ true }` with the brackets, as long as the brackets aren't there its good.

**Comment by mwitte98** [comment]
Just verified in postman that there are no brackets for both `/api/question/:id/submit_answer` and `/api/user/email_taken`. I'll update the code comments in my next PR so it's not confusing

**Pull request merged**
