### PR TITLE
New Practice View

### PR DESCRIPTION
**Pull request by 7imbrook**
Changes:
- New UI for practice on lesson creator
- Changed UI state for practices

@mwitte98 Posting to `/api/lesson/{id}/practice` just errors, can you confirm that works? Cause right now it just implodes.

### CODE REVIEW

**Review by djrenren — APPROVED** [review]
In case our sponsor looks at this, I wrote at least half of this.

**Comment by mwitte98** [comment]
@7imbrook it looks like [here](https://github.com/teamdotjs/v2/blob/djrenren/practice-view/client/src/actions/practice.ts#L14) that you are `POST`ing `'practice_generate'`. You need to `POST` a valid practice type (`'definition'`, `'synonym'`, `'root'`, or `'sentence'`) because it's an [enum](https://github.com/teamdotjs/v2/blob/djrenren/practice-view/app/models/practice.rb#L6)

**Comment by 7imbrook** [comment]
@mwitte98 I'm not posting anything ATM, are those changes in this branch?

**Comment by mwitte98** [comment]
@7imbrook If you're not posting anything then that's the error. We can't create a practice without having a type for the practice.

**Comment by 7imbrook** [comment]
@mwitte98 ok, I've done that, the error I've traced back to not all the word infos being filled out. We should check for that on the back end and give a better error than a stack trace.

**Comment by mwitte98** [comment]
@7imbrook not all wordinfos being filled out when trying to generate a practice? That's something I wanted to discuss with the team first, but it's on my todo list

**Pull request merged**
