### PR TITLE
Delete user_id from session when signed_in returns false

### PR DESCRIPTION
**Pull request by mwitte98**

### CODE REVIEW

**Comment by 7imbrook** [comment]
@mwitte98 shouldn't we delete the entire session?

**Comment by mwitte98** [comment]
@7imbrook the only thing I ever put in the session is user_id so I don't think it's necessary

**Comment by 7imbrook** [comment]
Does it work locally?

**Comment by mwitte98** [comment]
Yes, I haven't had any problems logging in locally. Changed both `session.delete(:user_id)` to be `reset_session` anyways

**Review by 7imbrook — APPROVED** [review]
Awesome

**Pull request merged**
