### PR TITLE
Change FITB underscores to a text field

### PR DESCRIPTION
**Pull request by mwitte98**
Related Issue #171 

Changes:
- Change FITB underscores to a text field

### CODE REVIEW

**Review by djrenren — CHANGES_REQUESTED** [review]
What's going on with that prompts slice map shenanigans? It looks like since we're only rendering one prompt we should just do that

**Comment by mwitte98** [comment]
@djrenren Since we are splitting on space, we lose all spaces unless we explicitly add them back in, like we do in the else clause. However, when we replace the underscores with a JSX element, we aren't including the space after the underscores. If the underscores at the end of the sentence, we also lose the ending punctuation mark. By adding an extra space, it adds the space that should be after the underscores and it separates the ending punctuation mark from the underscores so it's not removed. It's ugly, but it's the only way I could get it to work properly.

**Comment by mwitte98** [comment]
@djrenren Updated this based on your recommendation

**Comment by mwitte98** [comment]
@djrenren can you approve this?

**Comment by mwitte98** [comment]
Updated to include all characters following underscores, such as 'ed', 's', and punctuation.

@djrenren does this look better now?

**Review by djrenren — APPROVED** [review]
Lgtm

**Pull request merged**
