### PR TITLE
Sellers/logout

### PR DESCRIPTION
**Pull request by Valseer**
Related Issue #86 
Clears Issue #157 

Changes:
- User actions added
- Logout button added

Breaking Changes:
- none present

### CODE REVIEW

**Review by mwitte98 — APPROVED** [review]

**Review by 7imbrook — DISMISSED** [review]
Have you vertically centered that let?

**Comment by Valseer** [comment]
Hey @7imbrook if I'm reading [this ](https://github.com/callemall/material-ui/issues/773) right, the whole centering issue might be a current problem as of December of last year.

**Comment by Valseer** [comment]
@7imbrook Fixed the centering issue, sorta janky but it works so :/

**Review by 7imbrook — APPROVED** [review]
LGTM

**Pull request merged**
