### PR TITLE
Endpoint for login and a test endpoint for the token generated

### PR DESCRIPTION
**Pull request by mwitte98**
Related Issue #21 

Changes:
- Users db table created
- Endpoint for login that returns a json web token
- Test endpoint to verify the token works

### CODE REVIEW

**Comment by 7imbrook** [comment]
@mwitte98 I'm checking this now, but we were gonna just do session and not have any tokens? Does rails give us an authed session automatically? That will get checked on endpoints marked as needed auth? If we use session (over token based) there's little to no work that needs to deal with keeping auth on the client side.

**Comment by mwitte98** [comment]
@7imbrook rails 5 api doesn't have session middleware by default. I could add it in and store tokens in session cookies if that's easier?

**Comment by 7imbrook** [comment]
@mwitte98 yeah lets do that instead of Auth headers

**Review by 7imbrook — APPROVED** [review]
I'm gonna approve this so we can start having endpoints to hit, but we can move to sessions in a new PR

**Pull request merged**
